# Config for model
model:
  energy_model:
      "@name": "mace"
      species: ["H", "O"]
      cutoff: &cutoff 5.0
      # Model specific parameters
      l_max: 3
      hidden_irreps:  "64x0e + 64x1o + 64x2e + 64x3o"
      residual_first_interaction: true
  compute_force: true
  compute_stress: false
  compute_hessian: false
# Config for dataset
train_dataset:
  data_source: "data/water_train.xyz"
  index: ":"
  neighborlist_cutoff: *cutoff
  neighborlist_backend: &nbr_backend "matscipy"
  atomref_energies:
test_dataset:
  data_source: "data/water_test.xyz"
  index: ":"
  neighborlist_cutoff: *cutoff
  neighborlist_backend: *nbr_backend
val_size: 0.1
batch_size: 4
dataset_cache_dir: "data"
shift_by_avg_atomic_energy: true
scale_by_force_rms: true
dataset_scale_stride: null
trainable_scales: true

# Hyperparameters for training
## Global config
project_name: "water_molecule"
experiment_name: "mace_lmax_3"
train_force: True
train_stress: False
max_epochs: 5
device: "cuda"
restart_from_checkpoint: null
## Logging
logger: tensorboard
log_every_n_steps: 50
checkpoint_monitor: "val_loss"
checkpoint_mode: "min"
checkpoint_save_last: True

## Loss and metrics
loss_weights:
  energy: 1.00
  force: 1.00
  # stress: 1.0
loss_type: "mse_loss"
per_atom_energy_loss: true
metrics:
  - "energy_mae"
  - "per_atom_energy_mae"
  - "force_mae"
  # - "stress_mae"
  - "energy_rmse"
  - "per_atom_energy_rmse"
  - "force_rmse"
  # - "stress_rmse"

# Optimization
optimizer: "adam"
lr: 1.0e-3
weight_decay: 0.0
optimizer_kwargs:
  amsgrad: true
lr_scheduler: reduce_lr_on_plateau
lr_scheduler_kwargs:
  patience: 25
  factor: 0.5
  mode: "min"
  min_lr: 1.0e-6
early_stopping: True
early_stopping_monitor: "lr"
early_stopping_mode: "min"
early_stopping_patience: 100000000000
early_stopping_threshold: 1.0e-6
gradient_clip_val: 5.0
ema_decay: 0.995
