energy_model:
  "@name": mace
  species: ["C", "H"]        # Placeholder
  cutoff: 5.0                # Cutoff radius for neighbor list
  num_bessel: 8
  num_polynomial_cutoff: 5
  num_interactions: 2
  residual_first_interaction: false
  l_max: 3
  hidden_irreps: 64x0e + 64x1o + 64x2e + 64x3o
  correlation: 3
  MLP_irreps: 16x0e
  gate: silu
  atomic_energies: null
  avg_num_neighbors: null
compute_force: true          # Compute force or not
compute_stress: false        # Compute stress or not
compute_hessian: false       # Compute hessian or not
